version: "3"
services:
  mysql:
    image: mysql
    container_name: showcase-mysqldb
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysqlvol:/var/lib/mysql
  showcaseapi: 
    build: ./showcase_app/
    volumes:
      - ./showcase_app:/app
    ports:
      - "3000:80"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - SHOWCASE_URL=http://showcase:3000
volumes:
  mysqlvol:
