version: '3.1'
services:
  mysql:
    image: mysql:8.0
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=showcasedb
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/
  showcaseapi: 
    build: ./showcase_app/
    volumes:
      - ./showcase_app:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - SHOWCASE_URL=http://showcase:3000
    command: sh -c "/wait && /initscript"
    environment:
        - WAIT_HOSTS=mysql:3306
        - WAIT_HOSTS_TIMEOUT=300
        - WAIT_SLEEP_INTERVAL=30
        - WAIT_HOST_CONNECT_TIMEOUT=30
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment: 
      - PMA_HOST=mysql
      - PMA_PORT=3306
