version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: showcase-mysqldb
    ports: 
      - "3306:3306"
    
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - /var/lib/docker/volumes/mysqlvol/_data
  showcaseapi: 
    build: ./showcase_app/
    volumes:
      - ./showcase_app:/app
    ports:
      - "3000:80"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - SHOWCASE_URL=http://showcase:3000
