# Generated by Django 3.2.8 on 2021-11-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebshowcaseProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.IntegerField(default='', max_length=10)),
                ('projectName', models.CharField(default='', max_length=1000)),
                ('description', models.CharField(default='', max_length=1000)),
                ('verified', models.BooleanField(default=False)),
                ('course', models.CharField(max_length=100)),
                ('userId', models.IntegerField(default='', max_length=100)),
            ],
        ),
    ]
