# Generated by Django 3.2.8 on 2021-11-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webshowcaseproject',
            name='projectid',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='webshowcaseproject',
            name='userId',
            field=models.IntegerField(default=''),
        ),
    ]
