# Generated by Django 3.2.8 on 2021-11-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20211118_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectid', models.AutoField(db_column='projectID', primary_key=True, serialize=False)),
                ('projectname', models.CharField(db_column='projectName', max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('verified', models.IntegerField(blank=True, null=True)),
                ('course', models.CharField(max_length=255)),
                ('projectimage', models.CharField(blank=True, db_column='projectImage', max_length=255, null=True)),
                ('projectvideo', models.CharField(blank=True, db_column='projectVideo', max_length=255, null=True)),
                ('projectthumbnail', models.CharField(blank=True, db_column='projectThumbnail', max_length=255, null=True)),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='WebshowcaseProject',
        ),
    ]
