// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Showcase
//
//  Schemes:
//    http
//  Host: showcase.com
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
